import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from "react";
import { createClient } from '@layerzerolabs/scan-client';
const client = createClient('testnet');
import {getAllTheTxParameters} from '../server/data.js';

export default function Home() {
  //const status = useGetTransactionData(hash);


  const useGetTransactionData = (hash) =>{
    const [status, setStatus] = useState('');
    let msgStatus;
    client
      .getMessagesBySrcTxHash('0xaf38050c54da0d4f4242b11c37811ded98c1c13319ef2b8359843f38c39c269f')
      .then((result) => {
        console.log(result.messages);
        //'INFLIGHT' | 'DELIVERED' | 'FAILED';
        msgStatus = result.messages[0].status;
        while (msgStatus !== 'DELIVERED') {
          msgStatus = result.messages[0].status;
          console.log('check status: ' + msgStatus);
        }

        if(status === 'DELIVERED') {
          getAllTheTxParameters(result.messages)
          setStatus(result.messages[0].status)
          console.log('done');
        }

    });
    return status;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
          <button onClick={gettransaction} className={styles.button}> check-result</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
